migrateup:
	migrate -path migrations -database "mysql://root:root@(localhost:3307)/scrapper" -verbose up

migratedown:
	migrate -path migrations -database "mysql://root:root@(localhost:3307)/scrapper" -verbose down	