migrateup:
	migrate -path migrations -database "mysql://test:test@(localhost:3308)/api" -verbose up

migratedown:
	migrate -path migrations -database "mysql://test:test@(localhost:3308)/api" -verbose down	